// CAELINUS CODEX — freeze.mjs  (PHASE 0 — Archive Safety)
// Copies the irreplaceable text canon verbatim and writes a SHA256 integrity
// manifest for EVERY source + asset. Modifies no original. Re-runnable.
//   node codex/engine/freeze.mjs <isoDate>
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { ARCHIVE_ROOT, CODEX_ROOT, ASSET_DIR, SOURCES } from './config.mjs';

const DATE = process.argv[2] || 'undated';
const FREEZE = path.join(CODEX_ROOT, '_freeze', DATE);
const SRC_COPY = path.join(FREEZE, 'sources');
fs.mkdirSync(SRC_COPY, { recursive: true });
const rel = (p) => path.relative(ARCHIVE_ROOT, p).replace(/\\/g, '/');
const sha = (p) => { const h = crypto.createHash('sha256'); h.update(fs.readFileSync(p)); return h.digest('hex'); };

const rows = [];

// 1. copy text sources verbatim (small, most valuable)
for (const s of SOURCES) {
  const from = path.join(ARCHIVE_ROOT, s.file);
  const to = path.join(SRC_COPY, s.file);
  fs.copyFileSync(from, to);
  rows.push({ kind: 'source(copied)', file: rel(from), bytes: fs.statSync(from).size, sha256: sha(from) });
}
// also copy the tiny extra docs if present
for (const extra of ['CAELINUS ART BIBLE 001.txt']) { /* already in SOURCES */ }

// 2. hash-verify all assets (not duplicated here — 330MB; integrity manifest only)
let assetFiles = [];
try { assetFiles = fs.readdirSync(ASSET_DIR).filter(f => /\.(png|jpe?g|webp|gif)$/i.test(f)); } catch {}
for (const f of assetFiles.sort()) {
  const p = path.join(ASSET_DIR, f);
  rows.push({ kind: 'asset(hashed)', file: rel(p), bytes: fs.statSync(p).size, sha256: sha(p) });
}

// 3. write manifest
const totalBytes = rows.reduce((n, r) => n + r.bytes, 0);
let md = `<!-- CAELINUS CODEX — PHASE 0 FREEZE · generated by engine/freeze.mjs -->\n\n`;
md += `# FREEZE MANIFEST — ${DATE}\n\n`;
md += `> Kanonu düzeltmeden önce dondur. Metin kaynakları \`_freeze/${DATE}/sources/\` altına birebir kopyalandı. `;
md += `Tüm dosyalar (metin + ${assetFiles.length} görsel) SHA256 ile parmak izlendi. Hiçbir orijinal değiştirilmedi.\n\n`;
md += `- Kaynak metin: ${SOURCES.length} dosya (kopyalandı + hashlendi)\n`;
md += `- Görsel: ${assetFiles.length} dosya (hashlendi; 330MB olduğu için kopyalanmadı — istenirse tam kopya alınır)\n`;
md += `- Toplam: ${(totalBytes / 1024 / 1024).toFixed(1)} MB parmak izlendi\n\n`;
md += `## Bütünlük tablosu\n\n| Tür | Dosya | Bayt | SHA256 (ilk 16) |\n|---|---|---|---|\n`;
for (const r of rows) md += `| ${r.kind} | \`${r.file}\` | ${r.bytes} | \`${r.sha256.slice(0, 16)}\` |\n`;
md += `\n## Tam SHA256 (doğrulama için)\n\n\`\`\`\n`;
for (const r of rows) md += `${r.sha256}  ${r.file}\n`;
md += `\`\`\`\n`;
fs.writeFileSync(path.join(FREEZE, 'FREEZE_MANIFEST.md'), md, 'utf8');
fs.writeFileSync(path.join(FREEZE, 'checksums.sha256'),
  rows.map(r => `${r.sha256}  ${r.file}`).join('\n') + '\n', 'utf8');

console.log(`FREEZE ${DATE}: ${SOURCES.length} sources copied, ${rows.length} files hashed, ${(totalBytes/1024/1024).toFixed(1)} MB.`);
console.log(`→ ${rel(FREEZE)}/`);
